package com.ktsession.demosession;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TaskAction implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public TaskAction() {
    }




}