package com.ktsession.demosession;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TaskAction implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String decision;

	public TaskAction() {
	}

	public java.lang.String getDecision() {
		return this.decision;
	}

	public void setDecision(java.lang.String decision) {
		this.decision = decision;
	}

	public TaskAction(java.lang.String decision) {
		this.decision = decision;
	}

}